openapi: 3.1.0
info:
  title: Trophy
  version: '1.0.4'
paths:
  /achievements:
    get:
      description: Get all achievements and their completion stats.
      operationId: achievements_all
      tags:
        - Achievements
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AchievementWithStatsResponse'
              examples:
                Successful operation:
                  value:
                    - id: 5100fe51-6bce-6j44-b0hs-bddc4e123682
                      trigger: api
                      name: Finish onboarding
                      description: Complete the onboarding process.
                      badgeUrl: https://example.com/badge.png
                      key: finish-onboarding
                      completions: 8
                      completedPercentage: 80
                    - id: 5100fe51-6bce-6j44-b0hs-bddc4e123683
                      trigger: metric
                      name: 500 words written
                      description: Write 500 words in the app.
                      badgeUrl: https://example.com/badge.png
                      metricId: 5100fe51-6bce-6j44-b0hs-bddc4e123683
                      metricName: words written
                      metricValue: 500
                      completions: 6
                      completedPercentage: 60
                    - id: 5100fe51-6bce-6j44-b0hs-bddc4e123684
                      trigger: streak
                      name: 10 days of exercise
                      description: Exercise at least once a day for 10 days in a row.
                      badgeUrl: https://example.com/badge.png
                      streakLength: 10
                      completions: 2
                      completedPercentage: 20
        '401':
          description: 'Unauthorized'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorBody'
        '404':
          description: 'Achievements not found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorBody'
        '422':
          description: 'Unprocessible Entity'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorBody'
      summary: Get all achievements and their completion stats
      security:
        - ApiKeyAuth: []
  /achievements/{key}/complete:
    post:
      description: Mark an achievement as completed for a user.
      operationId: achievements_complete
      tags:
        - Achievements
      parameters:
        - name: key
          in: path
          description: Unique reference of the achievement as set when created.
          required: true
          schema:
            type: string
          example: finish-onboarding
      responses:
        '201':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AchievementCompletionResponse'
              examples:
                Successful operation:
                  value:
                    completionId: 0040fe51-6bce-4b44-b0ad-bddc4e123534
                    achievement:
                      id: 5100fe51-6bce-6j44-b0hs-bddc4e123682
                      trigger: api
                      name: Finish onboarding
                      description: Complete the onboarding process.
                      badgeUrl: https://example.com/badge.png
                      key: finish-onboarding
                      achievedAt: '2021-01-01T00:00:00Z'
        '401':
          description: 'Unauthorized'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorBody'
        '404':
          description: 'Achievement Not Found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorBody'
        '422':
          description: 'Unprocessible Entity'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorBody'
      summary: Mark an achievement as completed
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  $ref: '#/components/schemas/UpdatedUser'
                  description: The user that completed the achievement.
              required:
                - user
            examples:
              Successful operation:
                value:
                  user:
                    id: user-id
                    email: user@example.com
                    tz: Europe/London
                    subscribedToEmails: true
  /metrics/{key}/event:
    post:
      description: Increment or decrement the value of a metric for a user.
      operationId: metrics_event
      tags:
        - Metrics
      parameters:
        - name: key
          in: path
          description: Unique reference of the metric as set when created.
          required: true
          schema:
            type: string
          example: words-written
      responses:
        '201':
          description: Created event
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventResponse'
              examples:
                Successful operation:
                  value:
                    metricId: d01dcbcb-d51e-4c12-b054-dc811dcdc623
                    eventId: 0040fe51-6bce-4b44-b0ad-bddc4e123534
                    total: 750
                    achievements:
                      - id: 5100fe51-6bce-6j44-b0hs-bddc4e123682
                        trigger: metric
                        metricId: 5100fe51-6bce-6j44-b0hs-bddc4e123682
                        metricName: words written
                        metricValue: 500
                        name: 500 words written
                        description: Write 500 words in the app.
                        achievedAt: '2020-01-01T00:00:00Z'
                    currentStreak:
                      length: 1
                      frequency: daily
                      started: '2025-04-02'
                      periodStart: '2025-03-31'
                      periodEnd: '2025-04-05'
                      expires: '2025-04-12'
        '400':
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorBody'
        '401':
          description: 'Unauthorized'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorBody'
        '422':
          description: 'Unprocessible Entity'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorBody'
      summary: Send a metric change event
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  $ref: '#/components/schemas/UpsertedUser'
                  description: The user that triggered the event.
                value:
                  type: number
                  format: double
                  description: >-
                    The value to add to the user's current total for the given
                    metric.
                  example: 750
              required:
                - user
                - value
            examples:
              Successful operation:
                value:
                  user:
                    email: user@example.com
                    tz: Europe/London
                    id: '18'
                  value: 750
  /users:
    post:
      description: Identify a new user.
      operationId: users_create
      tags:
        - Users
      summary: Identify a new user
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              $ref: '#/components/schemas/UpsertedUser'
              description: The user object.
      responses:
        '201':
          description: Identified user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
                examples:
                  Successful operation:
                    value:
                      id: user-id
                      email: user@example.com
                      tz: Europe/London
                      subscribedToEmails: true
                      created: '2021-01-01T00:00:00Z'
                      updated: '2021-01-01T00:00:00Z'
        '400':
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorBody'
        '422':
          description: 'Unprocessible Entity'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorBody'
        '401':
          description: 'Unauthorized'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorBody'
  /users/{id}:
    get:
      description: Get a single user.
      operationId: users_get
      tags:
        - Users
      summary: Get a single user
      parameters:
        - name: id
          in: path
          description: ID of the user to get.
          required: true
          schema:
            type: string
          example: userId
      security:
        - ApiKeyAuth: []
      responses:
        '200':
          description: Found user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
                examples:
                  Successful operation:
                    value:
                      id: user-id
                      email: user@example.com
                      tz: Europe/London
                      subscribedToEmails: true
                      created: '2021-01-01T00:00:00Z'
                      updated: '2021-01-01T00:00:00Z'
        '400':
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorBody'
        '422':
          description: 'Unprocessible Entity'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorBody'
        '401':
          description: 'Unauthorized'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorBody'
    patch:
      description: Update a user.
      operationId: users_update
      tags:
        - Users
      summary: Update a user
      security:
        - ApiKeyAuth: []
      parameters:
        - name: id
          in: path
          description: ID of the user to update.
          required: true
          schema:
            type: string
          example: id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdatedUser'
              description: The user object.
            example:
              id: user-id
              email: user@example.com
              tz: Europe/London
      responses:
        '200':
          description: Updated user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
                examples:
                  Successful operation:
                    value:
                      id: user-id
                      email: user@example.com
                      tz: Europe/London
                      subscribedToEmails: true
                      created: '2021-01-01T00:00:00Z'
                      updated: '2021-01-01T00:00:00Z'
        '400':
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorBody'
        '422':
          description: 'Unprocessible Entity'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorBody'
        '401':
          description: 'Unauthorized'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorBody'
  /users/{id}/metrics:
    get:
      description: Get a single user's progress against all active metrics.
      operationId: users_all_metrics
      tags:
        - Users
      parameters:
        - name: id
          in: path
          description: ID of the user
          required: true
          schema:
            type: string
          example: userId
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MetricResponse'
              examples:
                Successful operation:
                  value:
                    - id: d01dcbcb-d51e-4c12-b054-dc811dcdc623
                      key: words-written
                      name: Words written
                      status: active
                      current: 4500
                      achievements:
                        - id: abe3120f-5ca9-4344-92c8-5b891643a04b
                          trigger: metric
                          name: Novice Writer
                          metricId: d01dcbcb-d51e-4c12-b054-dc811dcdc623
                          metricValue: 500
                          achievedAt: '2021-01-01T00:00:00Z'
                          badgeUrl: https://example.com/badge1.png
                        - id: 8a07f2d0-9c72-4de1-bf92-9530ae82b4b6
                          trigger: metric
                          name: Intermediate Writer
                          metricId: d01dcbcb-d51e-4c12-b054-dc811dcdc623
                          metricValue: 1000
                          achievedAt: '2021-01-02T00:00:00Z'
                          badgeUrl: https://example.com/badge2.png
                        - id: 2090d038-aa04-4048-ab2e-e2b7bf2d3b9f
                          trigger: metric
                          name: Expert Writer
                          metricId: d01dcbcb-d51e-4c12-b054-dc811dcdc623
                          metricValue: 2000
                          achievedAt: null
        '401':
          description: 'Unauthorized'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorBody'
        '404':
          description: 'User Not Found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorBody'
        '422':
          description: 'Unprocessible Entity'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorBody'
      summary: Get all metrics for a user
      security:
        - ApiKeyAuth: []
  /users/{id}/metrics/{key}:
    get:
      description: Get a user's progress against a single active metric.
      operationId: users_single_metric
      tags:
        - Users
      parameters:
        - name: id
          in: path
          description: ID of the user.
          required: true
          schema:
            type: string
          example: userId
        - name: key
          in: path
          description: Unique key of the metric.
          required: true
          schema:
            type: string
          example: key
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetricResponse'
              examples:
                Successful operation:
                  value:
                    id: d01dcbcb-d51e-4c12-b054-dc811dcdc623
                    key: words-written
                    name: Words written
                    status: active
                    current: 1500
                    achievements:
                      - id: abe3120f-5ca9-4344-92c8-5b891643a04b
                        trigger: metric
                        name: Novice Writer
                        metricId: d01dcbcb-d51e-4c12-b054-dc811dcdc623
                        metricValue: 500
                        achievedAt: '2021-01-01T00:00:00Z'
                      - id: 8a07f2d0-9c72-4de1-bf92-9530ae82b4b6
                        trigger: metric
                        name: Intermediate Writer
                        metricId: d01dcbcb-d51e-4c12-b054-dc811dcdc623
                        metricValue: 1000
                        achievedAt: '2021-01-02T00:00:00Z'
                      - id: 2090d038-aa04-4048-ab2e-e2b7bf2d3b9f
                        trigger: metric
                        name: Expert Writer
                        metricId: d01dcbcb-d51e-4c12-b054-dc811dcdc623
                        metricValue: 2000
                        achievedAt: null
                        badgeUrl: https://example.com/badge.png
        '401':
          description: 'Unauthorized'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorBody'
        '404':
          description: 'Not Found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorBody'
        '422':
          description: 'Unprocessible Entity'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorBody'
      summary: Get a single metric for a user
      security:
        - ApiKeyAuth: []
  /users/{id}/metrics/{key}/event-summary:
    get:
      description: Get a summary of metric events over time for a user.
      operationId: users_metric_event_summary
      tags:
        - Users
      parameters:
        - name: id
          in: path
          description: ID of the user.
          required: true
          schema:
            type: string
          example: userId
        - name: key
          in: path
          description: Unique key of the metric.
          required: true
          schema:
            type: string
          example: words-written
        - name: aggregation
          in: query
          description: The time period over which to aggregate the event data.
          required: true
          schema:
            type: string
            enum:
              - daily
              - weekly
              - monthly
          example: daily
        - name: startDate
          in: query
          description: The start date for the data range in YYYY-MM-DD format. The startDate must be before the endDate, and the date range must not exceed 400 days.
          required: true
          schema:
            type: string
            format: date
          example: '2024-01-01'
        - name: endDate
          in: query
          description: The end date for the data range in YYYY-MM-DD format. The endDate must be after the startDate, and the date range must not exceed 400 days.
          required: true
          schema:
            type: string
            format: date
          example: '2024-01-31'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    date:
                      type: string
                      format: date
                      description: The date of the data point. For weekly or monthly aggregations, this is the first date of the period.
                      example: '2024-01-01'
                    total:
                      type: number
                      format: double
                      description: The user's total for this metric at the end of this date.
                      example: 100
                    change:
                      type: number
                      format: double
                      description: The change in the user's total for this metric during this period.
                      example: 50
                  required:
                    - date
                    - total
                    - change
              examples:
                Successful operation:
                  value:
                    - date: '2024-01-01'
                      total: 100
                      change: 100
                    - date: '2024-01-02'
                      total: 300
                      change: 200
                    - date: '2024-01-03'
                      total: 600
                      change: 300
        '401':
          description: 'Unauthorized'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorBody'
        '404':
          description: 'Not Found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorBody'
        '422':
          description: 'Unprocessible Entity'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorBody'
      summary: Get a summary of metric events over time
      security:
        - ApiKeyAuth: []
  /users/{id}/achievements:
    get:
      description: Get all of a user's completed achievements.
      operationId: users_all_achievements
      tags:
        - Users
      parameters:
        - name: id
          in: path
          description: ID of the user.
          required: true
          schema:
            type: string
          example: userId
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CompletedAchievementResponse'
              examples:
                Successful operation:
                  value:
                    - id: d01dcbcb-d51e-4c12-b054-dc811dcdc625
                      trigger: api
                      key: completed-onboarding
                      name: Completed Onboarding
                      achievedAt: '2021-01-01T00:00:00Z'
                      badgeUrl: https://example.com/badge2.png
                    - id: d01dcbcb-d51e-4c12-b054-dc811dcdc623
                      trigger: metric
                      key: novice-writer
                      metricId: d01dcbcb-d51e-4c12-b054-dc811dcdc619
                      metricValue: 500
                      metricName: words written
                      name: Novice Writer
                      achievedAt: '2021-02-01T00:00:00Z'
                      badgeUrl: https://example.com/badge1.png
                    - id: d01dcbcb-d51e-4c12-b054-dc811dcdc624
                      trigger: streak
                      key: 3-day-streak
                      streakLength: 3
                      name: 3-Day Streak
                      achievedAt: '2021-03-01T00:00:00Z'
                      badgeUrl: https://example.com/badge2.png
        '401':
          description: 'Unauthorized'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorBody'
        '404':
          description: 'Not Found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorBody'
        '422':
          description: 'Unprocessible Entity'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorBody'
      summary: Get a user's completed achievements
      security:
        - ApiKeyAuth: []
  /users/{id}/streak:
    get:
      description: Get a user's streak data.
      operationId: users_streak
      tags:
        - Users
      parameters:
        - name: id
          in: path
          description: ID of the user.
          required: true
          schema:
            type: string
          example: userId
        - in: query
          name: historyPeriods
          schema:
            type: integer
            default: 7
          description: >-
            The number of past streak periods to include in the streakHistory field of the 
            response.
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/StreakResponse'
              examples:
                Successful operation:
                  value:
                    length: 1
                    frequency: weekly
                    started: '2025-04-02'
                    periodStart: '2025-03-31'
                    periodEnd: '2025-04-05'
                    expires: '2025-04-12'
                    streakHistory:
                      - periodStart: '2025-03-30'
                        periodEnd: '2025-04-05'
                        length: 1
                      - periodStart: '2025-04-06'
                        periodEnd: '2025-04-12'
                        length: 2
                      - periodStart: '2025-04-13'
                        periodEnd: '2025-04-19'
                        length: 3
                      - periodStart: '2025-04-20'
                        periodEnd: '2025-04-26'
                        length: 0
                      - periodStart: '2025-04-27'
                        periodEnd: '2025-05-03'
                        length: 1
                      - periodStart: '2025-05-04'
                        periodEnd: '2025-05-10'
                        length: 2
                      - periodStart: '2025-05-11'
                        periodEnd: '2025-05-17'
                        length: 3
        '401':
          description: 'Unauthorized'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorBody'
        '404':
          description: 'Not Found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorBody'
        '422':
          description: 'Unprocessible Entity'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorBody'
      summary: Get a user's streak status
      security:
        - ApiKeyAuth: []
  /users/{id}/points:
    get:
      description: Get a user's points.
      operationId: users_points
      tags:
        - Users
      parameters:
        - name: id
          in: path
          description: ID of the user.
          required: true
          schema:
            type: string
          example: userId
        - in: query
          name: awards
          schema:
            type: integer
            default: 10
            minimum: 1
            maximum: 100
          description: The number of recent point awards to return.
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetUserPointsResponse'
              examples:
                Successful operation:
                  value:
                    total: 100
                    awards:
                      - id: 0040fe51-6bce-4b44-b0ad-bddc4e123534
                        awarded: 10
                        trigger:
                          id: 0040fe51-6bce-4b44-b0ad-bddc4e123534
                          type: metric
                          points: 10
                          metricName: words written
                          metricThreshold: 1000
        '401':
          description: 'Unauthorized'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorBody'
        '404':
          description: 'Not Found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorBody'
        '422':
          description: 'Unprocessible Entity'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorBody'
      summary: Get a user's points data
      security:
        - ApiKeyAuth: []
  /users/{id}/points/event-summary:
    get:
      description: Get a summary of points awards over time for a user.
      operationId: users_points_event_summary
      tags:
        - Users
      parameters:
        - name: id
          in: path
          description: ID of the user.
          required: true
          schema:
            type: string
          example: userId
        - name: aggregation
          in: query
          description: The time period over which to aggregate the event data.
          required: true
          schema:
            type: string
            enum:
              - daily
              - weekly
              - monthly
          example: daily
        - name: startDate
          in: query
          description: The start date for the data range in YYYY-MM-DD format. The startDate must be before the endDate, and the date range must not exceed 400 days.
          required: true
          schema:
            type: string
            format: date
          example: '2024-01-01'
        - name: endDate
          in: query
          description: The end date for the data range in YYYY-MM-DD format. The endDate must be after the startDate, and the date range must not exceed 400 days.
          required: true
          schema:
            type: string
            format: date
          example: '2024-01-31'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    date:
                      type: string
                      format: date
                      description: The date of the data point. For weekly or monthly aggregations, this is the first date of the period.
                      example: '2024-01-01'
                    total:
                      type: number
                      format: double
                      description: The user's total points at the end of this date.
                      example: 100
                    change:
                      type: number
                      format: double
                      description: The change in the user's total points during this period.
                      example: 50
                  required:
                    - date
                    - total
                    - change
              examples:
                Successful operation:
                  value:
                    - date: '2024-01-01'
                      total: 100
                      change: 100
                    - date: '2024-01-02'
                      total: 300
                      change: 200
                    - date: '2024-01-03'
                      total: 600
                      change: 300
        '401':
          description: 'Unauthorized'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorBody'
        '404':
          description: 'Not Found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorBody'
        '422':
          description: 'Unprocessible Entity'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorBody'
      summary: Get a summary of points events over time
      security:
        - ApiKeyAuth: []
  /points/summary:
    get:
      description: Get a breakdown of the number of users with points in each range.
      operationId: points_summary
      tags:
        - Points
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PointsSummaryResponse'
              examples:
                Successful operation:
                  value:
                    - from: 0
                      to: 0
                      users: 5012
                    - from: 1
                      to: 100
                      users: 1501
                    - from: 101
                      to: 200
                      users: 1007
                    - from: 201
                      to: 300
                      users: 584
                    - from: 301
                      to: 400
                      users: 201
                    - from: 401
                      to: 500
                      users: 102
                    - from: 501
                      to: 600
                      users: 25
                    - from: 601
                      to: 700
                      users: 0
                    - from: 701
                      to: 800
                      users: 0
                    - from: 801
                      to: 900
                      users: 0
                    - from: 901
                      to: 1000
                      users: 0
        '401':
          description: 'Unauthorized'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorBody'
        '404':
          description: 'Not Found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorBody'
      summary: Get a breakdown of users by points
      security:
        - ApiKeyAuth: []
  /points/triggers:
    get:
      description: Get all points triggers.
      operationId: points_triggers
      tags:
        - Points
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PointsTriggerResponse'
              examples:
                Successful operation:
                  value:
                    - id: 0040fe51-6bce-4b44-b0ad-bddc4e123534
                      type: metric
                      points: 10
                      status: active
                      metricId: 0040fe51-6bce-4b44-b0ad-bddc4e123534
                      metricName: words written
                      metricThreshold: 1000
                      created: '2021-01-01T00:00:00Z'
                      updated: '2021-01-01T00:00:00Z'
                    - id: 0040fe51-6bce-4b44-b0ad-bddc4e123536
                      type: streak
                      points: 10
                      status: active
                      streakLengthThreshold: 7
                      created: '2021-01-01T00:00:00Z'
                      updated: '2021-01-01T00:00:00Z'
                    - id: 0040fe51-6bce-4b44-b0ad-bddc4e123535
                      type: achievement
                      points: 50
                      status: active
                      achievementId: 0040fe51-6bce-4b44-b0ad-bddc4e123535
                      achievementName: finish onboarding
                      created: '2021-01-01T00:00:00Z'
                      updated: '2021-01-01T00:00:00Z'
        '401':
          description: 'Unauthorized'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorBody'
      summary: Get all points triggers
      security:
        - ApiKeyAuth: []
components:
  schemas:
    MetricStatus:
      title: MetricStatus
      type: string
      enum:
        - archived
        - active
      description: The status of the achievement.
    StreakFrequency:
      title: StreakFrequency
      type: string
      enum:
        - daily
        - weekly
        - monthly
        - yearly
    BaseStreakResponse:
      title: Streak Response
      type: object
      properties:
        length:
          type: integer
          description: The length of the user's current streak.
        frequency:
          $ref: '#/components/schemas/StreakFrequency'
          description: The frequency of the streak.
        started:
          type: string
          format: date
          description: The date the streak started.
        periodStart:
          type: string
          format: date
          description: The start date of the current streak period.
        periodEnd:
          type: string
          format: date
          description: The end date of the current streak period.
        expires:
          type: string
          format: date
          description: The date the streak will expire if the user does not increment a metric.
      required:
        - length
        - frequency
    MetricEventStreakResponse:
      title: Streak Response (Metric Event)
      type: object
      description: An object representing the user's streak after sending a metric event.
      allOf:
        - $ref: '#/components/schemas/BaseStreakResponse'
        - type: object
          properties:
            extended:
              type: boolean
              description: Whether this metric event increased the user's streak length.
    StreakResponse:
      title: Streak Response
      type: object
      description: An object representing the user's streak.
      allOf:
        - $ref: '#/components/schemas/BaseStreakResponse'
        - type: object
          properties:
            streakHistory:
              type: array
              description: >-
                A list of the user's past streak periods up through the current period. Each
                period includes the start and end dates and the length of the streak.
              items:
                type: object
                description: >-
                  An object representing a past streak period.
                properties:
                  periodStart:
                    type: string
                    format: date
                    description: The date this streak period started.
                    example: '2025-03-31'
                  periodEnd:
                    type: string
                    format: date
                    description: The date this streak period ended.
                    example: '2025-04-05'
                  length:
                    type: integer
                    description: The length of the user's streak during this period.
                    example: 1
                required:
                  - periodStart
                  - periodEnd
                  - length
    PointsTrigger:
      title: PointsTrigger
      type: object
      properties:
        id:
          type: string
          description: The ID of the trigger
        type:
          type: string
          description: The type of trigger
          enum: ['metric', 'achievement', 'streak']
        points:
          type: number
          description: The points awarded by this trigger.
        metricName:
          type: string
          description: If the trigger has type 'metric', the name of the metric
        metricThreshold:
          type: number
          description: If the trigger has type 'metric', the threshold of the metric that triggers the points
        streakLengthThreshold:
          type: number
          description: If the trigger has type 'streak', the threshold of the streak that triggers the points
        achievementName:
          type: string
          description: If the trigger has type 'achievement', the name of the achievement
    PointsAward:
      title: PointsAward
      type: object
      properties:
        id:
          type: string
          description: The ID of the trigger award
        awarded:
          type: number
          description: The points awarded by this trigger
        trigger:
          $ref: '#/components/schemas/PointsTrigger'
    GetUserPointsResponse:
      title: GetUserPointsResponse
      type: object
      properties:
        total:
          type: number
          description: The user's total points
        awards:
          type: array
          description: Array of trigger awards that added points.
          items:
            $ref: '#/components/schemas/PointsAward'
    MetricEventPointsResponse:
      title: MetricEventPointsResponse
      type: object
      allOf:
        - $ref: '#/components/schemas/GetUserPointsResponse'
        - type: object
          properties:
            added:
              type: number
              description: The points added by this event.
              example: 10
    AchievementResponse:
      title: AchievementResponse
      type: object
      properties:
        id:
          type: string
          description: The unique ID of the achievement.
        name:
          type: string
          description: The name of this achievement.
        trigger:
          type: string
          enum: ['metric', 'streak', 'api']
          description: The trigger of the achievement.
        description:
          type: string
          description: The description of this achievement.
        badgeUrl:
          type: string
          description: >-
            The URL of the badge image for the achievement, if one has been
            uploaded.
        key:
          type: string
          description: The key used to reference this achievement in the API (only applicable if trigger = 'api')
        streakLength:
          type: integer
          description: The length of the streak required to complete the achievement (only applicable if trigger = 'streak')
        metricId:
          type: string
          description: The ID of the metric associated with this achievement (only applicable if trigger = 'metric')
        metricValue:
          type: number
          format: double
          description: >-
            The value of the metric required to complete the achievement (only applicable if trigger = 'metric')
        metricName:
          type: string
          description: The name of the metric associated with this achievement (only applicable if trigger = 'metric')
        currentStreak:
          $ref: '#/components/schemas/MetricEventStreakResponse'
          description: >-
            The user's current streak for the metric, if the metric has streaks
            enabled.
      required:
        - id
        - trigger
        - name
    CompletedAchievementResponse:
      title: CompletedAchievementResponse
      type: object
      allOf:
        - $ref: '#/components/schemas/AchievementResponse'
        - type: object
          properties:
            achievedAt:
              type: string
              format: date-time
              description: The date and time the achievement was completed, in ISO 8601 format.
    AchievementWithStatsResponse:
      title: AchievementWithStatsResponse
      type: object
      allOf:
        - $ref: '#/components/schemas/AchievementResponse'
        - type: object
          properties:
            completions:
              type: integer
              description: The number of users who have completed this achievement.
            completedPercentage:
              type: number
              format: double
              description: The percentage of all users who have completed this achievement.
    MetricResponse:
      title: MetricResponse
      type: object
      properties:
        id:
          type: string
          description: The unique ID of the metric.
          example: d01dcbcb-d51e-4c12-b054-dc811dcdc623
        key:
          type: string
          description: The unique key of the metric.
          example: words-written
        name:
          type: string
          description: The name of the metric.
          example: Words written
        status:
          $ref: '#/components/schemas/MetricStatus'
          description: The status of the metric.
        current:
          type: number
          format: double
          description: The user's current total for the metric.
          example: 1500
        achievements:
          type: array
          items:
            $ref: '#/components/schemas/CompletedAchievementResponse'
          description: >-
            A list of the metric's achievements and the user's progress towards
            each.
      required:
        - id
        - key
        - name
        - status
        - current
        - achievements
    UpdatedUser:
      title: Updated User
      type: object
      description: An object with editable user fields.
      properties:
        email:
          type: string
          description: The user's email address. Required if subscribeToEmails is true.
          example: user@example.com
        name:
          type: string
          description: The name to refer to the user by in emails.
          example: User
        tz:
          type: string
          description: The user's timezone (used for email scheduling).
          example: Europe/London
        subscribeToEmails:
          type: boolean
          default: true
          description: Whether the user should receive Trophy-powered emails. Cannot be false if an email is provided.
          example: true
    UpsertedUser:
      title: Upserted User
      type: object
      description: An object with editable user fields.
      allOf:
        - $ref: '#/components/schemas/UpdatedUser'
        - type: object
          properties:
            id:
              type: string
              description: The ID of the user in your database. Must be a string.
              example: user-id
          required:
            - id
    User:
      title: User
      type: object
      description: A user of your application.
      allOf:
        - $ref: '#/components/schemas/UpsertedUser'
        - type: object
          properties:
            control:
              type: boolean
              description: Whether the user is in the control group, meaning they do not receive emails or other communications from Trophy.
              example: false
            created:
              type: string
              format: date-time
              description: The date and time the user was created, in ISO 8601 format.
              example: '2021-01-01T00:00:00Z'
            updated:
              type: string
              format: date-time
              description: The date and time the user was last updated, in ISO 8601 format.
              example: '2021-01-01T00:00:00Z'
    ErrorBody:
      title: ErrorBody
      type: object
      properties:
        error:
          type: string
      required:
        - error
    AchievementCompletionResponse:
      title: AchievementCompletionResponse
      type: object
      properties:
        completionId:
          type: string
          description: The unique ID of the completion.
          example: 0040fe51-6bce-4b44-b0ad-bddc4e123534
        achievement:
          $ref: '#/components/schemas/CompletedAchievementResponse'
      required:
        - completionId
        - achievement
    EventResponse:
      title: EventResponse
      type: object
      properties:
        eventId:
          type: string
          description: The unique ID of the event.
          example: 0040fe51-6bce-4b44-b0ad-bddc4e123534
        metricId:
          type: string
          description: The unique ID of the metric that was updated.
          example: d01dcbcb-d51e-4c12-b054-dc811dcdc623
        total:
          type: number
          format: double
          description: The user's new total progress against the metric.
          example: 750
        achievements:
          type: array
          items:
            $ref: '#/components/schemas/CompletedAchievementResponse'
          description: Achievements completed as a result of this event.
        currentStreak:
          $ref: '#/components/schemas/MetricEventStreakResponse'
          description: >-
            The user's current streak for the metric, if the metric has streaks
            enabled.
        points:
          $ref: '#/components/schemas/PointsAward'
          description: >-
            The points added by this event, and a breakdown of the points
            awards that added points.
      required:
        - eventId
        - metricId
        - total
    PointsRange:
      title: PointsRange
      type: object
      properties:
        from:
          type: number
          description: The start of the points range. Inclusive.
        to:
          type: number
          description: The end of the points range. Inclusive.
        users:
          type: number
          description: The number of users in this points range.
    PointsSummaryResponse:
      title: PointsSummaryResponse
      type: array
      description: >-
        A list of eleven points ranges, with the first starting and ending at 0,
        and the remaining 10 being calculated as 10 equally sized ranges from 1
        to the greatest number of points a user has, rounded up to the nearest
        power of 10.
      items:
        $ref: '#/components/schemas/PointsRange'
    PointsTriggerResponse:
      title: PointsTriggerResponse
      type: object
      properties:
        id:
          type: string
          description: The unique ID of the trigger.
        type:
          type: string
          enum: ['metric', 'achievement', 'streak']
          description: The type of trigger.
        points:
          type: number
          description: The points awarded by this trigger.
        status:
          type: string
          enum: ['active', 'archived']
          description: The status of the trigger.
        achievementId:
          type: string
          description: The unique ID of the achievement associated with this trigger, if the trigger is an achievement.
        metricId:
          type: string
          description: The unique ID of the metric associated with this trigger, if the trigger is a metric.
        metricThreshold:
          type: number
          description: The amount that a user must increase the metric to earn the points, if the trigger is a metric.
        streakLengthThreshold:
          type: number
          description: The number of consecutive streak periods that a user must complete to earn the points, if the trigger is a streak.
        metricName:
          type: string
          description: The name of the metric associated with this trigger, if the trigger is a metric.
        achievementName:
          type: string
          description: The name of the achievement associated with this trigger, if the trigger is an achievement.
        created:
          type: string
          format: date-time
          description: The date and time the trigger was created, in ISO 8601 format.
        updated:
          type: string
          format: date-time
          description: The date and time the trigger was last updated, in ISO 8601 format.
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY
servers:
  - url: https://app.trophy.so/api
    description: Default
